### ISSUE TITLE
Graphical User Interface (GUI) Layout 

### ISSUE THREAD

**Issue by rofelmaetayoto** [xylabolos/17F-Madis#11]
May dalawa akong suggestion for layout natin. Tkinter yung gagamitin natin na GUI library.
Layout and placements lang muna ng mga tabs. Open for suggestions pa rin para mas maging better yung outcome.
![GUI 1](https://user-images.githubusercontent.com/105479288/170623654-864e3071-17a0-4956-816a-81e25bbf935e.jpg)
![GUI 2](https://user-images.githubusercontent.com/105479288/170623657-94427445-fe3c-42d9-a80a-3778101ef900.jpg)

**Comment by abriellecania** [comment]
niceeeee! pero saan na button ilagay ang exit?

**Comment by rofelmaetayoto** [comment]
Hello guys, ito na yung na edit ko para sa design ng stopwatch natin..
Pa help lang ako pa critique pleasee for enhancements :))
![1](https://user-images.githubusercontent.com/105479288/170672675-e7cdf52d-4d2f-4f6e-ab4b-3ea7f9b6c14a.jpg)
![2](https://user-images.githubusercontent.com/105479288/170672683-72f6235d-92f1-448e-aaeb-0d9eed8b4674.jpg)
