### ISSUE TITLE
Assign for Video Scripting 

### ISSUE THREAD

**Issue by xylabolos** [xylabolos/17F-Madis#2]
@arjelynenero ikaw ang naassign for video scripting for shooting sa video about the stopwatch and what's novel about it

**Comment by arjelynenero** [comment]
Ano nga concept ng video naten?

**Comment by arjelynenero** [comment]
Yong gipakita mo na video sa tiktok nong first meeting? @abriellecania

**Comment by abriellecania** [comment]
@arjelynenero uu, please review daw stopwatch natin baka you have something to add about it.
